CIONOM_ROOT_DIR = ../..

CIONOM_LIB_SOURCES = $(wildcard $(CIONOM_ROOT_DIR)/implementation/cionom/*.c)
CIONOM_LIB_OBJECTS = $(CIONOM_LIB_SOURCES:.c=$(OBJECT_SUFFIX))
CIONOM_LIB = lib/$(LIB_PREFIX)cionom$(DYNAMIC_LIB_SUFFIX)

CIONOM_EXEC_SOURCES = $(wildcard $(CIONOM_ROOT_DIR)/implementation/cli/*.c)
CIONOM_EXEC_OBJECTS = $(CIONOM_EXEC_SOURCES:.c=$(OBJECT_SUFFIX))
CIONOM_EXEC = $(CIONOM_ROOT_DIR)/cionom-cli$(EXECUTABLE_SUFFIX)

CIONOM_EXTERNAL_SOURCES = $(wildcard $(CIONOM_ROOT_DIR)/implementation/external/*.c)
CIONOM_EXTERNAL_OBJECTS = $(CIONOM_EXTERNAL_SOURCES:.c=$(OBJECT_SUFFIX))
CIONOM_EXTERNAL = lib/$(LIB_PREFIX)cionom-external$(DYNAMIC_LIB_SUFFIX)

CIONOM_LIB_CFLAGS = $(GEN_CORE_CFLAGS) -I$(CIONOM_ROOT_DIR)/implementation/cionom/include
CIONOM_LIB_LFLAGS = $(GEN_CORE_LFLAGS) -lcionom

build_message_cionom:
	@$(ECHO) "$(SECTION_PREFIX) Cíonom"
	@$(ECHO) "$(INFO_PREFIX) Cíonom Reference Implementation"

cionom: build_message_cionom $(CIONOM_EXEC) $(CIONOM_EXTERNAL) ### @Cíonom Builds the Cíonom reference implementation

$(CIONOM_LIB): CFLAGS = $(GEN_CORE_CFLAGS) -Wno-gnu-binary-literal
$(CIONOM_LIB): LFLAGS = -Llib $(GEN_CORE_LFLAGS)
$(CIONOM_LIB): $(CIONOM_LIB_OBJECTS)
$(CIONOM_LIB_OBJECTS): $(GEN_CORE_LIB)

$(CIONOM_EXEC): CFLAGS = $(CIONOM_LIB_CFLAGS)
$(CIONOM_EXEC): LFLAGS = -Llib $(CIONOM_LIB_LFLAGS)
$(CIONOM_EXEC): $(CIONOM_EXEC_OBJECTS)
$(CIONOM_EXEC_OBJECTS): $(CIONOM_LIB)

$(CIONOM_EXTERNAL): CFLAGS = $(CIONOM_LIB_CFLAGS)
$(CIONOM_EXTERNAL): LFLAGS = -Llib $(CIONOM_LIB_LFLAGS)
$(CIONOM_EXTERNAL): $(CIONOM_EXTERNAL_OBJECTS)
$(CIONOM_EXTERNAL_OBJECTS): $(CIONOM_LIB)

clean_cionom:
	@$(ECHO) "$(ACTION_PREFIX)"
	-rm $(CIONOM_LIB_OBJECTS)
	-rm $(CIONOM_LIB)
	-rm $(CIONOM_EXEC_OBJECTS)
	-rm $(CIONOM_EXEC)
	-rm $(CIONOM_EXTERNAL_OBJECTS)
	-rm $(CIONOM_EXTERNAL)
	@$(ECHO) "$(ACTION_SUFFIX)"
